{{- if .Values.wpokOperator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: worker-pool-operator
  labels:
    app.kubernetes.io/name: {{ include "wpok.fullname" . }}
    app.kubernetes.io/component: operator
rules:
  # Kopf peering / discovery
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Kopf runtime discovery
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Events (so-called “normal” kubectl describe)
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]

  # Admission webhooks (optional, Kopf uses if enabled)
  - apiGroups: [admissionregistration.k8s.io]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  # Application CRD + children
  - apiGroups: [hyperflow.agh.edu.pl]
    resources: [workerpools, workerpools/status, workerpools/finalizers]
    verbs: [get, list, watch, patch, create, update]

  - apiGroups: ["apps"]
    resources: [deployments, deployments/scale]
    verbs: ["*"]

  - apiGroups: ["monitoring.coreos.com"]
    resources: [prometheusrules]
    verbs: ["*"]

  - apiGroups: ["keda.sh"]
    resources: [scaledobjects]
    verbs: ["*"]
{{- end }}