{{- if and .Values.wpokOperator.enabled .Values.wpokOperator.secrets.rabbitAdmin }}
apiVersion: v1
kind: Secret
metadata:
  name: rabbit-admin
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "wpok.fullname" . }}
    app.kubernetes.io/component: operator
type: Opaque
stringData:
  username: {{ .Values.wpokOperator.secrets.rabbitAdmin.username | quote }}
  password: {{ .Values.wpokOperator.secrets.rabbitAdmin.password | quote }}
{{- end }}