{{- if .Values.wpokOperator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-pool-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "wpok.fullname" . }}
    app.kubernetes.io/component: operator
{{- end }}